# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: nice_nano_v2
#     shield: corne_left
#   - board: nice_nano_v2
#     shield: corne_right

include:
  - board: charybdis_left
    shield: splinky_v2_left
  - board: charybdis_right
    shield: splinky_v2_right
  - board: charybdis_left
    shield: splinky_v3_left
  - board: charybdis_right
    shield: splinky_v3_right
