- name: Create Shield Directory Structure
  run: |
    mkdir -p config/boards/shields/charybdis

- name: Create Shield Files
  run: |
    cat << 'EOF' > config/boards/shields/charybdis/charybdis.dtsi
    /*
     * Copyright (c) 2022 The ZMK Contributors
     *
     * SPDX-License-Identifier: MIT
     */

    #include <dt-bindings/zmk/matrix_transform.h>

    / {
        chosen {
            zmk,kscan = &kscan0;
            zmk,matrix_transform = &default_transform;
        };

        default_transform: keymap_transform_0 {
            compatible = "zmk,matrix-transform";
            columns = <12>;
            rows = <4>;
            map = 
    RC(0,0) RC(0,1) RC(0,2) RC(0,3) RC(0,4) RC(0,5)                 RC(0,6) RC(0,7) RC(0,8) RC(0,9) RC(0,10) RC(0,11)
    RC(1,0) RC(1,1) RC(1,2) RC(1,3) RC(1,4) RC(1,5)                 RC(1,6) RC(1,7) RC(1,8) RC(1,9) RC(1,10) RC(1,11)
    RC(2,0) RC(2,1) RC(2,2) RC(2,3) RC(2,4) RC(2,5)                 RC(2,6) RC(2,7) RC(2,8) RC(2,9) RC(2,10) RC(2,11)
    RC(3,0) RC(3,1) RC(3,2) RC(3,3) RC(3,4) RC(3,5) RC(3,6) RC(3,7) RC(3,8) RC(3,9) RC(3,10) RC(3,11) RC(3,12) RC(3,13)
                            RC(4,3) RC(4,4) RC(4,5) RC(4,6) RC(4,7) RC(4,8) RC(4,9) RC(4,10)
            >;
        };

        kscan0: kscan {
            compatible = "zmk,kscan-gpio-matrix";
            label = "KSCAN";
            diode-direction = "col2row";
        };

        left_encoder: encoder_left {
            compatible = "alps,ec11";
            label = "LEFT_ENCODER";
            a-gpios = <&gpio1 1 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
            b-gpios = <&gpio1 2 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
            resolution = <4>;
            status = "disabled";
        };

        right_encoder: encoder_right {
            compatible = "alps,ec11";
            label = "RIGHT_ENCODER";
            a-gpios = <&gpio1 1 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
            b-gpios = <&gpio1 2 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
            resolution = <4>;
            status = "disabled";
        };

        sensors {
            compatible = "zmk,keymap-sensors";
            sensors = <&left_encoder &right_encoder>;
            triggers-per-rotation = <20>;
        };
    };
    EOF

    cat << 'EOF' > config/boards/shields/charybdis/charybdis_left.overlay
    /*
     * Copyright (c) 2022 The ZMK Contributors
     *
     * SPDX-License-Identifier: MIT
     */

    #include "charybdis.dtsi"

    &default_transform {
        col-offset = <0>;
    };

    &kscan0 {
        col-gpios
            = <&gpio0 24 GPIO_ACTIVE_HIGH>
            , <&gpio0 22 GPIO_ACTIVE_HIGH>
            , <&gpio0 20 GPIO_ACTIVE_HIGH>
            , <&gpio0 18 GPIO_ACTIVE_HIGH>
            , <&gpio0 16 GPIO_ACTIVE_HIGH>
            , <&gpio0 14 GPIO_ACTIVE_HIGH>
            ;

        row-gpios
            = <&gpio0 31 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            , <&gpio0 29 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            , <&gpio0 2  (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            , <&gpio1 15 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            , <&gpio1 13 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            ;
    };

    &left_encoder {
        status = "okay";
    };
    EOF

    cat << 'EOF' > config/boards/shields/charybdis/charybdis_right.overlay
    /*
     * Copyright (c) 2022 The ZMK Contributors
     *
     * SPDX-License-Identifier: MIT
     */

    #include "charybdis.dtsi"

    &default_transform {
        col-offset = <6>;
    };

    &kscan0 {
        col-gpios
            = <&gpio0 14 GPIO_ACTIVE_HIGH>
            , <&gpio0 16 GPIO_ACTIVE_HIGH>
            , <&gpio0 18 GPIO_ACTIVE_HIGH>
            , <&gpio0 20 GPIO_ACTIVE_HIGH>
            , <&gpio0 22 GPIO_ACTIVE_HIGH>
            , <&gpio0 24 GPIO_ACTIVE_HIGH>
            ;

        row-gpios
            = <&gpio0 31 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            , <&gpio0 29 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            , <&gpio0 2  (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            , <&gpio1 15 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            , <&gpio1 13 (GPIO_ACTIVE_HIGH | GPIO_PULL_DOWN)>
            ;
    };

    &right_encoder {
        status = "okay";
    };
    EOF

- name: Check shield files
  run: |
    ls -la config/boards/shields/charybdis/
    cat config/boards/shields/charybdis/charybdis.dtsi | head -20
    cat config/boards/shields/charybdis/charybdis_left.overlay | head -10
    cat config/boards/shields/charybdis/charybdis_right.overlay | head -10