---
include:
  - board: nice_nano_v2
    shield: charybdis_qwerty_left
    keymap: qwerty
    format: bt
  - board: nice_nano_v2
    shield: charybdis_qwerty_right
    keymap: qwerty
    format: bt
  - board: nice_nano_v2
    shield: charybdis_qwerty_dongle
    keymap: qwerty
    format: dongle
    artifact-name: charybdis_qwerty_dongle_usb_dongle
  - board: nice_nano_v2
    shield: settings_reset
    format: settings
    artifact-name: firmware_reset_nano_v2
