name: Build

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.2
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: charybdis_left
          - board: nice_nano_v2
            shield: charybdis_right
          - board: nice_nano_v2
            shield: settings_reset
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: Configure Git for GitHub
        run: |
          git config --global url."https://github.com/".insteadOf git://github.com/
          # 인증없이 공개 저장소에 접근하기 위한 설정
          git config --global --add safe.directory '*'
      - name: West Update
        run: |
          # GitHub URLs로 직접 연결하는 방식으로 수정
          sed -i 's|url-base: https://github.com/perillamint|url-base: https://github.com/perillamint.git|g' config/west.yml
          sed -i 's|revision: charybdis-pmw3610|revision: refs/heads/charybdis-pmw3610|g' config/west.yml
          cat config/west.yml
          
          # GIT_TERMINAL_PROMPT=0으로 설정하여 인증 프롬프트 비활성화
          GIT_TERMINAL_PROMPT=0 west update || true
          
          # 실패한 경우 직접 클론
          if [ ! -d "zmk" ]; then
            echo "West update failed, trying direct clone..."
            mkdir -p zmk
            cd zmk
            git init
            git remote add origin https://github.com/perillamint/zmk.git
            git fetch --depth 1 origin charybdis-pmw3610
            git checkout FETCH_HEAD
            cd ..
          fi
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (${{ matrix.board }} - ${{ matrix.shield }})
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Rename artifacts
        if: ${{ matrix.shield != 'settings_reset' }}
        run: |
          mkdir -p artifacts
          cp build/zephyr/zmk.uf2 "artifacts/${{ matrix.shield }}.uf2"
      - name: Rename artifacts (settings_reset)
        if: ${{ matrix.shield == 'settings_reset' }}
        run: |
          mkdir -p artifacts
          cp build/zephyr/zmk.uf2 "artifacts/settings_reset.uf2"
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/*.uf2