name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-modules-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      
      - name: Create Shield Directory Structure
        run: |
          mkdir -p config/boards/shields/charybdis
      
      - name: Copy Shield Files
        run: |
          cp -v charybdis_left.overlay config/boards/shields/charybdis/
          cp -v charybdis_right.overlay config/boards/shields/charybdis/
          cp -v charybdis.dtsi config/boards/shields/charybdis/
      
      - name: Check directory structure
        run: |
          ls -la
          ls -la config/
          ls -la config/boards/shields/charybdis/
      
      - name: West Init
        run: west init -l config
      
      - name: Verify west.yml format
        run: |
          echo "Content of west.yml:"
          cat config/west.yml
          echo "Running YAML validation:"
          python3 -c "import yaml; yaml.safe_load(open('config/west.yml'))"
      
      - name: West Update
        run: west update --stats
      
      - name: West Zephyr export
        run: west zephyr-export
      
      - name: West Build (Charybdis Left Half)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=charybdis_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      
      - name: Charybdis Left Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: charybdis_left-zmk-firmware
          path: build/zephyr/zmk.uf2
      
      - name: West Build (Charybdis Right Half)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=charybdis_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      
      - name: Charybdis Right Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: charybdis_right-zmk-firmware
          path: build/zephyr/zmk.uf2